import { createLowlight, common } from "lowlight";
import ts from "highlight.js/lib/languages/typescript";
import js from "highlight.js/lib/languages/javascript";
import py from "highlight.js/lib/languages/python";
import go from "highlight.js/lib/languages/go";
import rust from "highlight.js/lib/languages/rust";
import sql from "highlight.js/lib/languages/sql";
import c from "highlight.js/lib/languages/c";
import cpp from "highlight.js/lib/languages/cpp";
import css from "highlight.js/lib/languages/css";
import html from "highlight.js/lib/languages/vbscript-html";
import bash from "highlight.js/lib/languages/bash";
import php from "highlight.js/lib/languages/php";
import ruby from "highlight.js/lib/languages/ruby";
import java from "highlight.js/lib/languages/java";
import csharp from "highlight.js/lib/languages/csharp";
import pwsh from "highlight.js/lib/languages/powershell";
import kotlin from "highlight.js/lib/languages/kotlin";
import lua from "highlight.js/lib/languages/lua";
import dart from "highlight.js/lib/languages/dart";
import swift from "highlight.js/lib/languages/swift";
import r from "highlight.js/lib/languages/r";
import dockerfile from "highlight.js/lib/languages/dockerfile";
import coffeescript from "highlight.js/lib/languages/coffeescript";


export const Registerlowlight = createLowlight(common);

Registerlowlight.register("ts", ts);
Registerlowlight.register("js", js);
Registerlowlight.register("py", py);
Registerlowlight.register("go", go);
Registerlowlight.register("rust", rust);
Registerlowlight.register("sql", sql);
Registerlowlight.register("c", c);
Registerlowlight.register("cpp", cpp);
Registerlowlight.register("css", css);
Registerlowlight.register("html", html);
Registerlowlight.register("bash", bash);
Registerlowlight.register("php", php);
Registerlowlight.register("ruby", ruby);
Registerlowlight.register("java", java);
Registerlowlight.register("csharp", csharp);
Registerlowlight.register("pwsh", pwsh);
Registerlowlight.register("kotlin", kotlin);
Registerlowlight.register("lua", lua);
Registerlowlight.register("swift", swift);
Registerlowlight.register("dart", dart);
Registerlowlight.register("r", r);
Registerlowlight.register("dockerfile", dockerfile);
Registerlowlight.register("coffeescript", coffeescript);